name: MERN Full CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.18.0'

      - name: Deploy backend to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to app folder on EC2
            mkdir -p /root/urtracker
            cd /root/urtracker

            # Clone repo if it doesn't exist
            if [ ! -d ".git" ]; then
              git clone https://github.com/Prabhmeetsingh087/UrTracker-CICD.git .
            fi

            # Pull latest code
            git fetch --all
            git reset --hard origin/main

            # Install server dependencies
            cd server
            npm install --production

            # Restart backend with PM2
            pm2 restart urtracker-server || pm2 start server.js --name urtracker-server
            pm2 save

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.18.0'

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build React app
        run: |
          cd client
          npm install
          npm run build
          ls -la build  # verify build folder exists

      - name: Deploy to S3
        run: |
          cd client
          aws s3 sync build s3://${{ secrets.S3_BUCKET }} --delete

      